### ISSUE TITLE
Add support for resource limiting

### ISSUE THREAD

**Issue by joestubbs** [TACC/abaco#27]
Proposal:
Global defaults for memory and cpu limits are provided as configurations in the [worker] stanza. Operators with elevated privileges can override these defaults when registering actors. These values are stored with the actor in the actors_store and are retrieved (and enforced) by the workers.

**Comment by mwvaughn** [comment]
Bumping this. I think we need at least a default limit to avoid some of the noisy-neighbor issues we're seeing under load.

**Comment by joestubbs** [comment]
Released in 0.12.0
