### ISSUE TITLE
autoscale

### ISSUE THREAD

**Issue by joestubbs** [TACC/abaco#5]
Allow users to register actors with an autoscale flag (TRUE/FALSE). With autoscale=true, abaco will run scheduled health checks to ensure that the number of workers is adequate for the given number of messages in the actor's message queue.

**Comment by deardooley** [comment]
Would this allow for actor pools to run a specific image? How is this accomplished now?

**Comment by joestubbs** [comment]
Yes. Right now, when an image is registered, a single worker is spawned to start containers for that image. This "single threaded" model conforms to the actor model, but for practical purposes, it seems useful to have abaco scale to allow a pool based on the queue size if the actor was set for autoscale at registration. 

The alternative is for the operator to register multiple actors with the same image, enabling them to handle scaling themselves.
