### ISSUE TITLE
Add "comment" or "description" field to nonces

### ISSUE THREAD

**Issue by mwvaughn** [TACC/abaco#57]
Once several nonces for a given actor are created and deployed out in the wild (i.e. as part of webhooks or handed out to trusted delegates) to enable various use cases, it becomes challenging to manage them since there's no obvious way of recalling how each nonce is used. One possible (and simple solution) is to add an optional "comment"-like field that can be populated when the nonce is requested. The contents of said field would then be returned as part of the nonce's record. 

**Example**

```json
{
  "actorId": "6rRKoBDgbzrjk",
  "apiServer": "https://api.tacc.cloud",
  "createTime": "2018-12-07 23:36:21.549079",
  "currentUses": 5,
  "description": "Github integration",
  "id": "TACC_rVv5P1RWWNPkY",
  "lastUseTime": "None",
  "level": "EXECUTE",
  "maxUses": -1,
  "owner": "tacobot",
  "remainingUses": -1,
  "roles": [
    "Internal/TACC_tacobot_jenkins_PRODUCTION",
    "Internal/TACC_tacobot_statusio_jul2018_PRODUCTION",
    "Internal/everyone"
  ]
}
```

**Comment by NotChristianGarcia** [comment]
Resolved in PR #72
