### ISSUE TITLE
Allow actors to configure log exipry

### ISSUE THREAD

**Issue by joestubbs** [TACC/abaco#82]
Tenant could specify a valid window (e.g., 1 day - 1 week) along with the default .

**Comment by NotChristianGarcia** [comment]
Added context.
Light information about database organization here. Log data is in the logs_store collection in Abaco's Mongo database.
https://github.com/TACC/abaco/blob/master/docs/developer_docs.md

Expiration is currently set true or false by a flag in the abaco config. If true, expiration will happen. The time to expire (log_ex) is set in abaco config. What we're looking for is making this log_ex configurable based on different things.

Levels of expiry time.
- Actor: Look for actor configured log_ex. Some kind of input at actor time.
- Tenant: Look for '{tenant}_log_ex' config in abaco.conf, if found use that. Actor is not allowed to go higher than this.
- Global: If actor or tenant expiry not set, use global log_ex.

**Comment by joestubbs** [comment]
Released as part of 1.7.0.
